### ISSUE TITLE
点击添加授权的时候报错

### ISSUE THREAD

**Issue by lsa620620** [chunbo007/wechat-mp#10]
授权事件中找不到记录，但转发记录中有数据
2024-06-27 10:41:51 pid:1 Worker process terminated with ERROR: E_ERROR "During inheritance of ArrayAccess: Uncaught ErrorException: Return type of EasyWeChat\Kernel\Support\Collection::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\wechat-mp-master\vendor\overtrue\wechat\src\Kernel\Support\Collection.php:367
Stack trace:
#0 D:\wechat-mp-master\vendor\overtrue\wechat\src\Kernel\Support\Collection.php(25): support\App::{closure}()
#1 D:\wechat-mp-master\vendor\composer\ClassLoader.php(576): include('...')
#2 D:\wechat-mp-master\vendor\composer\ClassLoader.php(427): Composer\Autoload\{closure}()
#3 D:\wechat-mp-master\vendor\overtrue\wechat\src\Kernel\Config.php(21): Composer\Autoload\ClassLoader->loadClass()
#4 D:\wechat-mp-master\vendor\composer\ClassLoader.php(576): include('...')
#5 D:\wechat-mp-master\vendor\composer\ClassLoader.php(427): Composer\Autoload\{closure}()
#6 D:\wechat-mp-master\vendor\overtrue\wechat\src\Kernel\Providers\ConfigServiceProvider.php(36): Composer\Autoload\ClassLoader->loadClass()
#7 D:\wechat-mp-master\vendor\pimple\pimple\src\Pimple\Container.php(122): EasyWeChat\Kernel\Providers\ConfigServiceProvider->EasyWeChat\Kernel\Providers\{closure}()
#8 D:\wechat-mp-master\vendor\overtrue\wechat\src\Kernel\Providers\LogServiceProvider.php(36): Pimple\Container->offsetGet()
#9 D:\wechat-mp-master\vendor\pimple\pimple\src\Pimple\Container.php(122): EasyWeChat\Kernel\Providers\LogServiceProvider->EasyWeChat\Kernel\Providers\{closure}()
#10 D:\wechat-mp-master\vendor\overtrue\wechat\src\Kernel\Providers\LogServiceProvider.php(45): Pimple\Container->offsetGet()
#11 D:\wechat-mp-master\vendor\pimple\pimple\src\Pimple\Container.php(297): EasyWeChat\Kernel\Providers\LogServiceProvider->register()
#12 D:\wechat-mp-master\vendor\overtrue\wechat\src\Kernel\ServiceContainer.php(164): Pimple\Container->register()
#13 D:\wechat-mp-master\vendor\overtrue\wechat\src\Kernel\ServiceContainer.php(71): EasyWeChat\Kernel\ServiceContainer->registerProviders()
#14 D:\wechat-mp-master\vendor\overtrue\wechat\src\Factory.php(39): EasyWeChat\Kernel\ServiceContainer->__construct()
#15 D:\wechat-mp-master\vendor\overtrue\wechat\src\Factory.php(52): EasyWeChat\Factory::make()
#16 D:\wechat-mp-master\app\common\service\wechat\OpenPlatform.php(31): EasyWeChat\Factory::__callStatic()
#17 D:\wechat-mp-master\app\admin\controller\MiniProgramController.php(109): app\common\service\wechat\OpenPlatform->__construct()
#18 D:\wechat-mp-master\vendor\workerman\webman-framework\src\App.php(319): app\admin\controller\MiniProgramController->getPcAuthorizerUrl()
#19 D:\wechat-mp-master\vendor\workerman\webman-framework\src\App.php(349): Webman\App::Webman\{closure}()
#20 D:\wechat-mp-master\app\admin\middleware\AuthCheck.php(43): Webman\App::Webman\{closure}()
#21 D:\wechat-mp-master\vendor\workerman\webman-framework\src\App.php(341): app\admin\middleware\AuthCheck->process()
#22 D:\wechat-mp-master\app\common\middleware\StaticFile.php(34): Webman\App::Webman\{closure}()
#23 D:\wechat-mp-master\vendor\workerman\webman-framework\src\App.php(341): app\common\middleware\StaticFile->process()
#24 D:\wechat-mp-master\vendor\workerman\webman-framework\src\App.php(168): Webman\App::Webman\{closure}()
#25 D:\wechat-mp-master\vendor\workerman\workerman\Connection\TcpConnection.php(646): Webman\App->onMessage()
#26 D:\wechat-mp-master\vendor\workerman\workerman\Events\Select.php(311): Workerman\Connection\TcpConnection->baseRead()
#27 D:\wechat-mp-master\vendor\workerman\workerman\Worker.php(1488): Workerman\Events\Select->loop()
#28 D:\wechat-mp-master\vendor\workerman\workerman\Worker.php(1405): Workerman\Worker::forkWorkersForWindows()
#29 D:\wechat-mp-master\vendor\workerman\workerman\Worker.php(560): Workerman\Worker::forkWorkers()
#30 D:\wechat-mp-master\vendor\workerman\webman-framework\src\support\App.php(131): Workerman\Worker::runAll()
#31 D:\wechat-mp-master\start.php(4): support\App::run()
#32 {main} in D:\wechat-mp-master\vendor\overtrue\wechat\src\Kernel\Support\Collection.php on line 25"

**Comment by lsa620620** [comment]
证书问题，已经解决
